# Generated by Django 6.0.3 on 2026-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('score', models.ImageField(upload_to='')),
                ('sub', models.CharField()),
            ],
        ),
    ]
